name: Deploy Streamlit App

on:
  push:
    branches:
      - master  # Adjust this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'  # Adjust to your required Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Streamlit
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        mkdir -p ~/.streamlit
        echo "[API_key]" > ~/.streamlit/secrets.toml
        echo "api_key = \"$OPENAI_API_KEY\"" >> ~/.streamlit/secrets.toml
        streamlit run app.py
